language: python
python:
- "2.7"
install:
- pip install 'setuptools>=18.5'
- pip install -r requirements.txt
script: tox
after_success:
  - python-codacy-coverage -r coverage.xml
sudo: false
cache: pip
